# Generated by Django 4.0.4 on 2022-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourism',
            name='imageurl',
            field=models.ImageField(default='abc.jpg', upload_to='Images'),
        ),
    ]
