# Generated by Django 4.0.4 on 2022-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('place_name', models.CharField(max_length=50)),
                ('tour_price', models.FloatField(default=100)),
                ('total_persons', models.IntegerField()),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TouristInfo',
            },
        ),
    ]
