# Generated by Django 4.0.4 on 2022-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_touristinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristinfo',
            name='total_persons',
            field=models.CharField(max_length=50),
        ),
    ]
