# Generated by Django 4.0.4 on 2022-06-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_touristinfo_total_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristinfo',
            name='tour_price',
            field=models.CharField(max_length=100),
        ),
    ]
