# Generated by Django 4.0.4 on 2022-06-20 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_touristinfo_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristinfo',
            name='booked_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 13, 47, 5, 140241, tzinfo=utc)),
        ),
    ]
