# Generated by Django 4.0.4 on 2022-06-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_touristinfo_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristinfo',
            name='booked_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
