# Generated by Django 4.0.4 on 2022-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_payment_expiry_alter_touristinfo_place_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristinfo',
            name='total_price',
            field=models.CharField(default=5, max_length=100),
        ),
    ]
